In [15]:
import pandas as pd

In [16]:
df = pd.read_csv('D:\OneDrive - NITT\Custom_Download\MCA-2nd_DataMining - Sheet1.csv')

<>:1: SyntaxWarning: invalid escape sequence '\O'
<>:1: SyntaxWarning: invalid escape sequence '\O'
C:\Users\avitr\AppData\Local\Temp\ipykernel_22364\2199822744.py:1: SyntaxWarning: invalid escape sequence '\O'
  df = pd.read_csv('D:\OneDrive - NITT\Custom_Download\MCA-2nd_DataMining - Sheet1.csv')

In [17]:
df

,Roll Number,Unnamed: 1,31-7-2024(10Q),7-8-2024(6Q),14-8-2024 (7Q),28-8-2024 (6Q),11-9-2024 (1Q),06/11/2024(LAB_FINAL_EXAM)
0,205123001,2.0,10.0,6.0,7.0,6.0,1.0,5.0
1,205123003,0.5,5.0,NaN,4.0,NaN,1.0,5.0
2,205123005,2.0,10.0,6.0,6.0,NaN,1.0,5.0
3,205123007,NaN,NaN,NaN,3.0,6.0,NaN,3.0
4,205123009,1.5,NaN,6.0,7.0,6.0,1.0,5.0
5,205123011,0.5,5.0,6.0,NaN,6.0,1.0,5.0
6,205123013,4.0,10.0,NaN,6.0,6.0,0.9,5.0
7,205123015,0.5,10.0,6.0,7.0,NaN,1.0,5.0
8,205123017,NaN,5.0,3.0,7.0,5.0,1.0,5.0
9,205123019,0.0,5.0,3.0,NaN,6.0,1.0,5.0
10,205123021,0.5,10.0,6.0,5.0,6.0,NaN,4.0
11,205123023,1.0,10.0,3.0,6.0,5.0,1.0,4.0
12,205123025,2.0,5.0,6.0,4.0,5.0,1.0,5.0
13,205123027,0.5,10.0,6.0,5.0,6.0,1.0,3.0
14,205123029,NaN,10.0,2.0,4.0,4.0,1.0,5.0
15,205123031,NaN,10.0,NaN,4.0,4.0,1.0,5.0
16,205123033,2.0,10.0,6.0,7.0,6.0,1.0,5.0
17,205123035,0.0,10.0,NaN,7.0,4.0,1.0,3.0
18,205123037,0.5,9.0,NaN,7.0,NaN,1.0,5.0
19,205123039,3.0,9.0,6.0,7.0,6.0,1.0,5.0
20,205123041,1.0,8.0,NaN,6.0,6.0,1.0,4.0
21,205123043,2.0,5.0,NaN,4.0,6.0,1.0,3.5
22,205123045,1.0,10.0,6.0,6.0,6.0,1.0,5.0
23,205123047,NaN,10.0,6.0,7.0,NaN,1.0,3.0
24,205123049,0.5,10.0,NaN,2.0,NaN,1.0,4.0
25,205123051,0.0,5.0,6.0,NaN,6.0,1.0,3.0
26,205123053,1.5,3.0,3.0,6.0,6.0,0.9,3.0
27,205123055,2.5,8.0,6.0,7.0,6.0,1.0,3.0
28,205123057,1.5,10.0,6.0,7.0,NaN,1.0,4.0
29,205123059,2.5,NaN,6.0,7.0,6.0,1.0,5.0
30,205123061,0.0,7.0,NaN,7.0,4.0,NaN,2.0
31,205123063,3.0,10.0,3.0,5.0,NaN,1.0,5.0
32,205123065,1.0,5.0,NaN,3.0,6.0,1.0,5.0
33,205123067,0.0,10.0,6.0,7.0,NaN,1.0,5.0
34,205123069,0.0,10.0,NaN,6.0,6.0,1.0,4.0
35,205123071,3.0,10.0,6.0,7.0,6.0,1.0,5.0
36,205123073,2.5,10.0,3.0,2.0,6.0,NaN,5.0
37,205123075,NaN,5.0,6.0,7.0,NaN,1.0,5.0
38,205123077,1.5,9.0,6.0,7.0,6.0,1.0,3.0
39,205123079,4.0,10.0,NaN,6.0,NaN,0.9,4.0
40,205123081,0.5,2.0,NaN,4.0,NaN,1.0,4.5
41,205123083,1.0,10.0,6.0,7.0,6.0,1.0,3.5
42,205123085,0.5,5.0,NaN,7.0,6.0,1.0,2.5
43,205123087,0.5,10.0,6.0,7.0,NaN,1.0,5.0
44,205123089,0.0,9.0,3.0,7.0,NaN,1.0,3.0
45,205123091,0.0,5.0,6.0,NaN,5.0,1.0,5.0
46,205123093,0.5,10.0,6.0,7.0,6.0,0.9,5.0
47,205123095,4.0,10.0,NaN,6.0,6.0,1.0,5.0
48,205123097,1.0,10.0,6.0,7.0,6.0,1.0,5.0
49,205123099,1.0,10.0,4.0,6.0,6.0,1.0,5.0
50,205123101,0.5,5.0,6.0,7.0,4.0,NaN,5.0
51,205123103,1.0,10.0,6.0,7.0,6.0,1.0,5.0
52,205123105,2.0,10.0,NaN,7.0,5.0,1.0,5.0
53,205123107,NaN,5.0,1.0,5.0,4.0,1.0,3.5
54,205123109,1.5,10.0,NaN,7.0,NaN,1.0,5.0
55,205123111,1.0,10.0,6.0,7.0,NaN,0.9,4.0
56,205123113,0.0,10.0,6.0,7.0,6.0,1.0,5.0

In [18]:
df = df.rename(columns={'Unnamed: 1': 'Weekly_20', '06/11/2024(LAB_FINAL_EXAM)': 'EndSem_30'})

In [20]:
df.Weekly_20 = df.Weekly_20*4

In [23]:
df.EndSem_30 = df.EndSem_30*5.5

In [25]:
df = df.rename(columns={'31-7-2024(10Q)': 'Weekly1_20'})

In [27]:
df.Weekly1_20 = df.Weekly1_20*2

In [30]:
df.to_csv('mca_dm.csv',index=False)

In [53]:
df = pd.read_csv('mca_dm.csv')

In [54]:
df['11-9-2024 (1Q)'] = df['11-9-2024 (1Q)']*11

In [55]:
df['CT1'] = df[['7-8-2024(6Q)' ,'14-8-2024 (7Q)' ,'28-8-2024 (6Q)' ,'11-9-2024 (1Q)']].sum(axis=1)

In [57]:
df = df[['Roll Number','Weekly_20','Weekly1_20','EndSem_30','CT1']]

In [60]:
df.columns = ['Roll Number', 'Weekly1_20', 'Weekly2_20','EndSem_30' ,'CT1_30']

In [63]:
import numpy as np

In [66]:
df.Weekly1_20 = np.where(df.Weekly1_20==0,4,df.Weekly1_20)

C:\Users\avitr\AppData\Local\Temp\ipykernel_22364\543228424.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.Weekly1_20 = np.where(df.Weekly1_20==0,4,df.Weekly1_20)

In [67]:
df.Weekly1_20 = np.where(df.Weekly1_20==0,4,df.Weekly1_20)

    Roll Number  Weekly1_20  Weekly2_20  EndSem_30  CT1_30
0     205123001           8          20      27.50    30.0
1     205123003           2          10      27.50    23.0
2     205123005           8          20      27.50    28.0
3     205123007           8          10      16.50    22.9
4     205123009           6          18      27.50    30.0
5     205123011           2          10      27.50    28.0
6     205123013          16          20      27.50    25.9
7     205123015           2          20      27.50    28.0
8     205123017          12          10      27.50    26.0
9     205123019           4          10      27.50    25.0
10    205123021           2          20      22.00    28.0
11    205123023           4          20      22.00    25.0
12    205123025           8          10      27.50    26.0
13    205123027           2          20      16.50    28.0
14    205123029          12          20      27.50    21.0
15    205123031          12          20      27.50    24.0
16    205123033           8          20      27.50    30.0
17    205123035           4          20      16.50    27.0
18    205123037           2          18      27.50    27.0
19    205123039          12          18      27.50    30.0
20    205123041           4          16      22.00    28.0
21    205123043           8          10      19.25    26.0
22    205123045           4          20      27.50    29.0
23    205123047          10          20      16.50    28.0
24    205123049           2          20      22.00    23.0
25    205123051           4          10      16.50    27.0
26    205123053           6          12      16.50    24.9
27    205123055          10          16      16.50    30.0
28    205123057           6          20      22.00    29.0
29    205123059          10          16      27.50    30.0
30    205123061           4          14      11.00    27.0
31    205123063          12          20      27.50    25.0
32    205123065           4          10      27.50    26.0
33    205123067           4          20      27.50    29.0
34    205123069           4          20      22.00    28.0
35    205123071          12          20      27.50    30.0
36    205123073          10          20      27.50    22.0
37    205123075          12          10      27.50    30.0
38    205123077           6          18      16.50    30.0
39    205123079          16          20      22.00    26.9
40    205123081           2          12      24.75    26.0
41    205123083           4          20      19.25    30.0
42    205123085           2          10      13.75    28.0
43    205123087           2          20      27.50    30.0
44    205123089           4          18      16.50    26.0
45    205123091           4          10      27.50    27.0
46    205123093           2          20      27.50    28.9
47    205123095          16          20      27.50    29.0
48    205123097           4          20      27.50    30.0
49    205123099           4          20      27.50    27.0
50    205123101           2          10      27.50    28.0
51    205123103           4          20      27.50    30.0
52    205123105           8          20      27.50    29.0
53    205123107          12          10      19.25    21.0
54    205123109           6          20      27.50    29.0
55    205123111           4          20      22.00    27.9
56    205123113           4          20      27.50    30.0

In [71]:
df['Total'] = df[['Weekly1_20', 'Weekly2_20','EndSem_30' ,'CT1_30']].sum(axis=1)

C:\Users\avitr\AppData\Local\Temp\ipykernel_22364\3011901590.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Total'] = df[['Weekly1_20', 'Weekly2_20','EndSem_30' ,'CT1_30']].sum(axis=1)

In [76]:
df = df.sort_values('Total',ascending=False)

In [78]:
df.to_csv('Final_mca_dm.csv',index=False)

In [80]:
df.Total.mean()

74.51140350877192

In [82]:
df.EndSem_30 = df.EndSem_30.round()

In [88]:
df = df.astype(int)

In [90]:
df['Total'] = df[['Weekly1_20', 'Weekly2_20','EndSem_30' ,'CT1_30']].sum(axis=1)

In [91]:
df

    Roll Number  Weekly1_20  Weekly2_20  EndSem_30  CT1_30  Total
47    205123095          16          20         28      29     93
35    205123071          12          20         28      30     90
6     205123013          16          20         28      25     89
19    205123039          12          18         28      30     88
0     205123001           8          20         28      30     86
16    205123033           8          20         28      30     86
39    205123079          16          20         22      26     84
52    205123105           8          20         28      29     85
31    205123063          12          20         28      25     85
15    205123031          12          20         28      24     84
2     205123005           8          20         28      28     84
29    205123059          10          16         28      30     84
54    205123109           6          20         28      29     83
51    205123103           4          20         28      30     82
48    205123097           4          20         28      30     82
56    205123113           4          20         28      30     82
4     205123009           6          18         28      30     82
14    205123029          12          20         28      21     81
22    205123045           4          20         28      29     81
33    205123067           4          20         28      29     81
43    205123087           2          20         28      30     80
37    205123075          12          10         28      30     80
36    205123073          10          20         28      22     80
49    205123099           4          20         28      27     79
46    205123093           2          20         28      28     78
7     205123015           2          20         28      28     78
28    205123057           6          20         22      29     77
8     205123017          12          10         28      26     76
18    205123037           2          18         28      27     75
23    205123047          10          20         16      28     74
34    205123069           4          20         22      28     74
55    205123111           4          20         22      27     73
41    205123083           4          20         19      30     73
27    205123055          10          16         16      30     72
10    205123021           2          20         22      28     72
12    205123025           8          10         28      26     72
11    205123023           4          20         22      25     71
38    205123077           6          18         16      30     70
20    205123041           4          16         22      28     70
45    205123091           4          10         28      27     69
17    205123035           4          20         16      27     67
5     205123011           2          10         28      28     68
32    205123065           4          10         28      26     68
50    205123101           2          10         28      28     68
24    205123049           2          20         22      23     67
9     205123019           4          10         28      25     67
13    205123027           2          20         16      28     66
40    205123081           2          12         25      26     65
44    205123089           4          18         16      26     64
21    205123043           8          10         19      26     63
1     205123003           2          10         28      23     63
53    205123107          12          10         19      21     62
26    205123053           6          12         16      24     58
25    205123051           4          10         16      27     57
3     205123007           8          10         16      22     56
30    205123061           4          14         11      27     56
42    205123085           2          10         14      28     54

In [93]:
df = df.sort_values('Total',ascending=False)

In [94]:
df.to_csv('Final_mca_dm.csv',index=False)

In [95]:
df

    Roll Number  Weekly1_20  Weekly2_20  EndSem_30  CT1_30  Total
47    205123095          16          20         28      29     93
35    205123071          12          20         28      30     90
6     205123013          16          20         28      25     89
19    205123039          12          18         28      30     88
0     205123001           8          20         28      30     86
16    205123033           8          20         28      30     86
52    205123105           8          20         28      29     85
31    205123063          12          20         28      25     85
39    205123079          16          20         22      26     84
15    205123031          12          20         28      24     84
2     205123005           8          20         28      28     84
29    205123059          10          16         28      30     84
54    205123109           6          20         28      29     83
56    205123113           4          20         28      30     82
4     205123009           6          18         28      30     82
48    205123097           4          20         28      30     82
51    205123103           4          20         28      30     82
14    205123029          12          20         28      21     81
22    205123045           4          20         28      29     81
33    205123067           4          20         28      29     81
43    205123087           2          20         28      30     80
37    205123075          12          10         28      30     80
36    205123073          10          20         28      22     80
49    205123099           4          20         28      27     79
46    205123093           2          20         28      28     78
7     205123015           2          20         28      28     78
28    205123057           6          20         22      29     77
8     205123017          12          10         28      26     76
18    205123037           2          18         28      27     75
23    205123047          10          20         16      28     74
34    205123069           4          20         22      28     74
55    205123111           4          20         22      27     73
41    205123083           4          20         19      30     73
27    205123055          10          16         16      30     72
10    205123021           2          20         22      28     72
12    205123025           8          10         28      26     72
11    205123023           4          20         22      25     71
38    205123077           6          18         16      30     70
20    205123041           4          16         22      28     70
45    205123091           4          10         28      27     69
32    205123065           4          10         28      26     68
50    205123101           2          10         28      28     68
5     205123011           2          10         28      28     68
17    205123035           4          20         16      27     67
24    205123049           2          20         22      23     67
9     205123019           4          10         28      25     67
13    205123027           2          20         16      28     66
40    205123081           2          12         25      26     65
44    205123089           4          18         16      26     64
21    205123043           8          10         19      26     63
1     205123003           2          10         28      23     63
53    205123107          12          10         19      21     62
26    205123053           6          12         16      24     58
25    205123051           4          10         16      27     57
3     205123007           8          10         16      22     56
30    205123061           4          14         11      27     56
42    205123085           2          10         14      28     54

In [97]:
import json
with open('final_words.json', 'r') as json_file:
    final_dict = json.load(json_file)

In [100]:
import pandas as pd

In [101]:
len(final_dict)

434920

In [103]:
pd.DataFrame(list(final_dict)).to_csv('junk.csv',index=False)