In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r'D:\OneDrive - NITT\Custom_Download\arc.csv')

In [7]:
df = df[['Payout Date','Payout Amount']]

In [10]:
df = df.groupby('Payout Date').sum()

In [13]:
df = df.reset_index()

In [16]:
df['Payout Date'] = pd.DatetimeIndex(df['Payout Date'])

In [36]:
df = df.sort_values('Payout Date').reset_index(drop=True)
df

   Payout Date  Payout Amount
0   2023-04-05        2101.07
1   2023-04-12         651.76
2   2023-04-19         537.56
3   2023-04-26         641.74
4   2023-05-03         546.80
5   2023-05-10         273.19
6   2023-05-17         737.46
7   2023-05-24         479.70
8   2023-05-31         309.10
9   2023-06-07         225.61
10  2023-06-14          78.57
11  2023-06-21         379.28
12  2023-06-28         647.66
13  2023-07-05         293.71
14  2023-07-12         286.00
15  2023-07-19         395.72
16  2023-07-26         671.68
17  2023-08-02         426.75
18  2023-08-09         529.36
19  2023-08-16         347.14
20  2023-08-23         213.36
21  2023-08-30         146.34
22  2023-09-06         194.40
23  2023-09-13         227.40
24  2023-09-20          67.21
25  2023-09-27         377.74
26  2023-10-04         223.37
27  2023-10-11         190.35
28  2023-10-18         348.43
29  2023-10-25        1048.13
30  2023-11-01         166.44
31  2023-11-08         336.20
32  2023-11-15         475.60
33  2023-11-22          23.40
34  2023-12-06         150.48
35  2023-12-20          85.73
36  2023-12-27         467.40
37  2024-01-03          16.38
38  2024-01-10         145.80
39  2024-01-24         117.45
40  2024-01-31          29.64
41  2024-02-07          90.78
42  2024-02-14         162.00
43  2024-02-21         170.37
44  2024-02-28         311.60
45  2024-03-06         239.02
46  2024-03-13         410.00
47  2024-03-20          91.73
48  2024-03-27          46.83

In [49]:
df

   Payout Date  Payout Amount       total
0   2023-04-05        2101.07  173338.275
1   2023-04-12         651.76   53770.200
2   2023-04-19         537.56   44348.700
3   2023-04-26         641.74   52943.550
4   2023-05-03         546.80   45111.000
5   2023-05-10         273.19   22538.175
6   2023-05-17         737.46   60840.450
7   2023-05-24         479.70   39575.250
8   2023-05-31         309.10   25500.750
9   2023-06-07         225.61   18612.825
10  2023-06-14          78.57    6482.025
11  2023-06-21         379.28   31290.600
12  2023-06-28         647.66   53431.950
13  2023-07-05         293.71   24231.075
14  2023-07-12         286.00   23595.000
15  2023-07-19         395.72   32646.900
16  2023-07-26         671.68   55413.600
17  2023-08-02         426.75   35206.875
18  2023-08-09         529.36   43672.200
19  2023-08-16         347.14   28639.050
20  2023-08-23         213.36   17602.200
21  2023-08-30         146.34   12073.050
22  2023-09-06         194.40   16038.000
23  2023-09-13         227.40   18760.500
24  2023-09-20          67.21    5544.825
25  2023-09-27         377.74   31163.550
26  2023-10-04         223.37   18428.025
27  2023-10-11         190.35   15703.875
28  2023-10-18         348.43   28745.475
29  2023-10-25        1048.13   86470.725
30  2023-11-01         166.44   13731.300
31  2023-11-08         336.20   27736.500
32  2023-11-15         475.60   39237.000
33  2023-11-22          23.40    1930.500
34  2023-12-06         150.48   12414.600
35  2023-12-20          85.73    7072.725
36  2023-12-27         467.40   38560.500
37  2024-01-03          16.38    1351.350
38  2024-01-10         145.80   12028.500
39  2024-01-24         117.45    9689.625
40  2024-01-31          29.64    2445.300
41  2024-02-07          90.78    7489.350
42  2024-02-14         162.00   13365.000
43  2024-02-21         170.37   14055.525
44  2024-02-28         311.60   25707.000
45  2024-03-06         239.02   19719.150
46  2024-03-13         410.00   33825.000
47  2024-03-20          91.73    7567.725
48  2024-03-27          46.83    3863.475

In [48]:
df['total'] = df['Payout Amount']*82.5

In [41]:
df1 = pd.read_csv(r'D:\OneDrive - NITT\Custom_Download\FederalBank (1).csv')

In [42]:
df1 = df1[df1['Particulars'].apply(lambda x: 'WISE' in x)]

In [43]:
df1 = df1[['Tran Date','Particulars','Deposit']]

In [44]:
df1['Tran Date'] = pd.DatetimeIndex(df1['Tran Date'])

C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '27-03-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '20-03-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '13-03-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '28-02-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '21-02-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '14-02-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '31-01-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '24-01-2024' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '27-12-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '20-12-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '22-11-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '15-11-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '25-10-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '18-10-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '27-09-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '20-09-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '13-09-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '30-08-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '23-08-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '16-08-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '26-07-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '19-07-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '28-06-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '21-06-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '14-06-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '31-05-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '24-05-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '17-05-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '26-04-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(
C:\Users\avitr\anaconda3\envs\test_env\lib\site-packages\pandas\core\indexes\datetimes.py:327: UserWarning: Parsing '19-04-2023' in DD/MM/YYYY format. Provide format or specify infer_datetime_format=True for consistent parsing.
  dtarr = DatetimeArray._from_sequence_not_strict(

In [45]:
df1.dtypes

Tran Date      datetime64[ns]
Particulars            object
Deposit               float64
dtype: object

In [46]:
df1 = df1.sort_values('Tran Date').reset_index(drop=True)
df1

    Tran Date                                        Particulars    Deposit
0  2023-01-11  FT IMPS/IFI/330509516320/WISE PAYMENTS LIMITE/...   13743.56
1  2023-02-08  FT IMPS/IFI/321408565394/WISE PAYMENTS LIMITE/...   34920.67
2  2023-03-05  FT IMPS/IFI/312308530859/WISE PAYMENTS LIMITE/...   44376.30
3  2023-04-10  FT IMPS/IFI/327709571300/WISE PAYMENTS LIMITE/...   18445.59
4  2023-04-19  FT IMPS/IFI/310908503078/WISE PAYMENTS LIMITE/...   43805.73
5  2023-04-26  FT IMPS/IFI/311608519745/WISE PAYMENTS LIMITE/...   52237.91
6  2023-05-04  FT IMPS/IFI/309514582107/WISE PAYMENTS LIMITE/...   39530.31
7  2023-05-04  FT IMPS/IFI/309512571864/WISE PAYMENTS LIMITE/...  131795.60
8  2023-05-07  FT IMPS/IFI/318607511417/WISE PAYMENTS LIMITE/...   23915.50
9  2023-05-17  FT IMPS/IFI/313710517280/WISE PAYMENTS LIMITE/...   60277.82
10 2023-05-24  FT IMPS/IFI/314410553365/WISE PAYMENTS LIMITE/...   39369.69
11 2023-05-31  FT IMPS/IFI/315111559242/WISE PAYMENTS LIMITE/...   25356.40
12 2023-06-09  FT IMPS/IFI/324908598796/WISE PAYMENTS LIMITE/...   16021.84
13 2023-06-12  FT IMPS/IFI/334008589251/WISE PAYMENTS LIMITE/...   12436.36
14 2023-06-14  FT IMPS/IFI/316508580461/WISE PAYMENTS LIMITE/...    6389.29
15 2023-06-21  FT IMPS/IFI/317211551579/WISE PAYMENTS LIMITE/...   30922.95
16 2023-06-28  FT IMPS/IFI/317909563122/WISE PAYMENTS LIMITE/...   52748.12
17 2023-07-06  FT IMPS/IFI/315808553448/WISE PAYMENTS LIMITE/...   18467.44
18 2023-07-19  FT IMPS/IFI/320008509469/WISE PAYMENTS LIMITE/...   32274.98
19 2023-07-26  FT IMPS/IFI/320708541757/WISE PAYMENTS LIMITE/...   54659.94
20 2023-08-11  FT IMPS/IFI/331209530510/WISE PAYMENTS LIMITE/...   27791.35
21 2023-08-16  FT IMPS/IFI/322808555089/WISE PAYMENTS LIMITE/...   28709.46
22 2023-08-23  FT IMPS/IFI/323508581743/WISE PAYMENTS LIMITE/...   17579.76
23 2023-08-30  FT IMPS/IFI/324208584966/WISE PAYMENTS LIMITE/...   11990.67
24 2023-09-08  FT IMPS/IFI/322109559343/WISE PAYMENTS LIMITE/...   43548.56
25 2023-09-13  FT IMPS/IFI/325608565475/WISE PAYMENTS LIMITE/...   18705.18
26 2023-09-20  FT IMPS/IFI/326308524357/WISE PAYMENTS LIMITE/...    5527.51
27 2023-09-27  FT IMPS/IFI/327009541465/WISE PAYMENTS LIMITE/...   31216.03
28 2023-10-05  FT IMPS/IFI/313008543350/WISE PAYMENTS LIMITE/...   22237.69
29 2023-10-18  FT IMPS/IFI/329108527458/WISE PAYMENTS LIMITE/...   28794.94
30 2023-10-25  FT IMPS/IFI/329808562980/WISE PAYMENTS LIMITE/...   86481.60
31 2023-11-10  FT IMPS/IFI/328408584214/WISE PAYMENTS LIMITE/...   15707.52
32 2023-11-15  FT IMPS/IFI/331909513504/WISE PAYMENTS LIMITE/...   39230.33
33 2023-11-22  FT IMPS/IFI/332608518709/WISE PAYMENTS LIMITE/...    1907.78
34 2023-12-04  FT IMPS/IFI/310207552778/WISE PAYMENTS LIMITE/...   53093.55
35 2023-12-07  FT IMPS/IFI/319308503574/WISE PAYMENTS LIMITE/...   23381.41
36 2023-12-20  FT IMPS/IFI/335408546771/WISE PAYMENTS LIMITE/...    7055.96
37 2023-12-27  FT IMPS/IFI/336108568644/WISE PAYMENTS LIMITE/...   38881.28
38 2024-01-24  FT IMPS/IFI/402409587271/WISE PAYMENTS LIMITE/...    9677.25
39 2024-01-31  FT IMPS/IFI/403108535188/WISE PAYMENTS LIMITE/...    2418.05
40 2024-02-14  FT IMPS/IFI/404508501247/WISE PAYMENTS LIMITE/...   13347.26
41 2024-02-21  FT IMPS/IFI/405208522848/WISE PAYMENTS LIMITE/...   14007.65
42 2024-02-28  FT IMPS/IFI/405908597442/WISE PAYMENTS LIMITE/...   25640.23
43 2024-03-01  FT IMPS/IFI/400308508542/WISE PAYMENTS LIMITE/...    1326.01
44 2024-03-13  FT IMPS/IFI/407308557494/WISE PAYMENTS LIMITE/...   33713.26
45 2024-03-20  FT IMPS/IFI/408008506223/WISE PAYMENTS LIMITE/...    7537.22
46 2024-03-27  FT IMPS/IFI/408708524644/WISE PAYMENTS LIMITE/...    3848.11
47 2024-06-03  FT IMPS/IFI/406609536170/WISE PAYMENTS LIMITE/...   19663.03
48 2024-07-02  FT IMPS/IFI/403809563812/WISE PAYMENTS LIMITE/...    7461.65
49 2024-10-01  FT IMPS/IFI/401009561303/WISE PAYMENTS LIMITE/...   12018.86

In [47]:
78*83

6474